### ISSUE TITLE
Crash while analysing Ant

### ISSUE THREAD

**Issue by cptanalatriste** [danikgan/COMP0138#3]
While trying to obtain all the commits for Ant, this error started to appear:

```
*** ComparePMDandDIFF: Error reading pmd-alerts.txt.
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:756)
	at java.lang.StringBuilder.delete(StringBuilder.java:244)
	at features.analyse.ComparePMDandDIFF.findLine(ComparePMDandDIFF.java:143)
	at features.analyse.ComparePMDandDIFF.findInPMD(ComparePMDandDIFF.java:109)
	at features.analyse.ComparePMDandDIFF.<init>(ComparePMDandDIFF.java:79)
	at features.AnalysedLink.usePMDonCommit(AnalysedLink.java:111)
	at features.AnalysedLink.<init>(AnalysedLink.java:46)
	at Main.analysing(Main.java:103)
	at Main.main(Main.java:34)
```

**Comment by danikgan** [comment]
Seems to be fixed, right?
