### ISSUE TITLE
Crashes when restarting analysis

### ISSUE THREAD

**Issue by cptanalatriste** [danikgan/COMP0138#4]
After updating the last version and trying to rerun the analysis, the program crashes:

```
/usr/lib/jvm/java-8-oracle/bin/java -javaagent:/snap/intellij-idea-ultimate/114/lib/idea_rt.jar=43689:/snap/intellij-idea-ultimate/114/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-oracle/jre/lib/javaws.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-oracle/jre/lib/plugin.jar:/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/home/carlos/COMP0138/production/COMP0138:/home/carlos/git/COMP0138/libs/commons-collections4-4.2.jar:/home/carlos/git/COMP0138/libs/commons-compress-1.18.jar:/home/carlos/git/COMP0138/libs/poi-4.0.1.jar:/home/carlos/git/COMP0138/libs/poi-ooxml-4.0.1.jar:/home/carlos/git/COMP0138/libs/poi-ooxml-schemas-4.0.1.jar:/home/carlos/git/COMP0138/libs/xbean.jar Main
*** Script v2.3.3

Select one of the operations:
1. Use "links.txt" to analyse Git using PMD.
2. Use "records.xlsx" for Bugzilla.
3. Delete all temporary files. (USED FOR TESTING)
Press '0' for exit.
1
Are you on MacOS (M), Linux (L) or Windows (W)?
(E) for else:	(Hint: your operating system is Linux.)
L
Specify the path for the text document, containing links and their corresponding number of commits to download. State the folders after: 
/home/carlos/sandbox/

Pre-processing...
Path: /home/carlos/sandbox//
*** ReadTXTInput: Error reading the TXT file.
*** Failed to proceed. Check the txt file.
PMD version: 6.10.0

*** Your respond is required to proceed.
It has been detected that the previous termination of this script was abrupt.
If you wish to restart, make sure projects that were downloaded during the latest execution are deleted now.
If you wish to continue, then the project should not have been deleted.
Otherwise, it will influence your results.
Do you with to continue the previous analysis (c) or restart (r)?
r
Restarting the analysis...
Deleting old repositories...
java.lang.NullPointerException
	at first.preprocessing.PreviousStatus.deleteRepositories(PreviousStatus.java:92)
	at first.preprocessing.PreviousStatus.<init>(PreviousStatus.java:61)
	at GitPMDAnalyser.preProcessing(GitPMDAnalyser.java:70)
	at GitPMDAnalyser.<init>(GitPMDAnalyser.java:34)
	at Main.menu(Main.java:26)
	at Main.main(Main.java:12)
Execution completed: false
*** Main: Error returning projectExists.
java.lang.NullPointerException
	at GitPMDAnalyser$Termination.run(GitPMDAnalyser.java:103)

Done.

Process finished with exit code 0
```

This is the only line in links.txt:

`0 https://gitbox.apache.org/repos/asf/ant.git
`

**Comment by danikgan** [comment]
State your repository as "_/home/carlos/sandbox_", not "_/home/carlos/sandbox/_". The "_/_" at the ends is added automatically. This is the reason it could not find the input txt.

**Comment by danikgan** [comment]
I can add an easy fix to check whether you added "/" at the end or not. I will upload it in the next commit. Stay tuned!

**Comment by danikgan** [comment]
Done so. Please check the new update.

**Comment by danikgan** [comment]
Also, check that your input (links.txt) is in the correct repository.

**Comment by cptanalatriste** [comment]
Solved! Is working now :)
